In [7]:
import pandas as pd
import dataframe_image as dfi

In [2]:
df = pd.read_csv("asx_etp_202401.csv")

In [8]:
top5 = df.head(5)
dfi.export(top5, "top5.png")

In [17]:
df[['ticker','name']].head(5)

  ticker                                    name
0   A200            Betashares Australia 200 ETF
1    IOZ            iShares Core S&P/ASX 200 ETF
2    ILC                  iShares S&P/ASX 20 ETF
3    MVW      VanEck Australian Equal Weight ETF
4    QOZ  Betashares FTSE RAFI Australia 200 ETF

In [38]:
df

,ticker,sector,name,mer,fum,fum_change,inflow_outflow,transacted_value,transacted_volume,no_of_trades,monthly_liquidity,spred,last_price,distribution_yield,one_month_return,one_year_return,three_year_return,five_year_returns
0,A200,Equity - Australia,Betashares Australia 200 ETF,0.04,"4,296.27",317.96,301.35,"214,355,402","1,719,165","14,021",4.99%,0.02%,127.46,3.70%,1.48%,8.44%,11.52%,11.30%
1,IOZ,Equity - Australia,iShares Core S&P/ASX 200 ETF,0.05,"5,122.88",296.04,275.6,"277,699,870","9,191,717","19,182",5.42%,0.04%,30.84,3.80%,1.34%,8.36%,11.08%,11.02%
2,ILC,Equity - Australia,iShares S&P/ASX 20 ETF,0.24,596.46,12,7.28,"25,625,586","870,614","1,928",4.30%,0.06%,29.95,4.18%,1.88%,9.61%,13.24%,12.50%
3,MVW,Equity - Australia,VanEck Australian Equal Weight ETF,0.35,"2,098.95",-20.77,21.72,"63,499,076","1,830,950","5,696",3.03%,0.05%,35.2,3.66%,0.36%,6.53%,9.32%,9.65%
4,QOZ,Equity - Australia,Betashares FTSE RAFI Australia 200 ETF,0.40,500.09,5.86,9.99,"15,187,004","1,005,650","1,952",3.04%,0.10%,15.44,5.07%,2.24%,9.74%,13.42%,11.75%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,XSOAI,Australian Indices,S&P/ASX Small Ords Accumulation,NaN,n/a,n/a,NaN,n/a,n/a,n/a,NaN,NaN,"9,771.10",NaN,0.90%,2.10%,1.33%,5.44%
327,XPJAI,Australian Indices,S&P/ASX 200 A-REIT Accumulation,NaN,n/a,n/a,NaN,n/a,n/a,n/a,NaN,NaN,"66,091.92",NaN,1.31%,10.18%,7.60%,5.09%
328,XIFAI,Australian Indices,S&P/ASX Infrastructure Index Accumulation,NaN,n/a,n/a,NaN,n/a,n/a,n/a,NaN,NaN,659.9,NaN,-1.79%,7.30%,14.85%,8.46%
329,SPBDASXT,Australian Indices,S&P/ASX Aust Fixed Int Idx Total Return,NaN,n/a,n/a,NaN,n/a,n/a,n/a,NaN,NaN,169.84,NaN,0.00%,0.00%,0.00%,2.35%
330,SPBDAGVT,Australian Indices,S&P/ASX Govt Bond Idx Total Return,NaN,n/a,n/a,NaN,n/a,n/a,n/a,NaN,NaN,169.97,NaN,0.00%,0.00%,0.00%,2.41%

In [41]:
df['fum'] = df['fum'].str.replace(',', '')
df['fum'] = pd.to_numeric(df['fum'], errors = 'coerce')

In [43]:
df.query('sector == "Equity - Australia"')

min_fum = 4000
df.query('sector == "Equity - Australia" and fum > @min_fum')

,ticker,sector,name,mer,fum,fum_change,inflow_outflow,transacted_value,transacted_volume,no_of_trades,monthly_liquidity,spred,last_price,distribution_yield,one_month_return,one_year_return,three_year_return,five_year_returns
0,A200,Equity - Australia,Betashares Australia 200 ETF,0.04,4296.27,317.96,301.35,"214,355,402","1,719,165","14,021",4.99%,0.02%,127.46,3.70%,1.48%,8.44%,11.52%,11.30%
1,IOZ,Equity - Australia,iShares Core S&P/ASX 200 ETF,0.05,5122.88,296.04,275.6,"277,699,870","9,191,717","19,182",5.42%,0.04%,30.84,3.80%,1.34%,8.36%,11.08%,11.02%
5,STW,Equity - Australia,SPDR S&P/ASX 200,0.05,4987.77,68.49,10.03,"160,793,439","2,394,568","8,203",3.22%,0.03%,68.97,4.17%,1.19%,8.39%,11.20%,11.12%
7,VAS,Equity - Australia,Vanguard Australian Shares Index ETF,0.07,14584.16,200.17,149.9,"526,705,742","5,686,560","48,813",3.61%,0.02%,94.74,3.66%,1.36%,8.01%,10.69%,11.04%

We can leverage function from `pandas` package `read_csv` and print top 5 rows by using `head` function.

```
import pandas as pd

df = pd.read_csv("asx_etp_202401.csv")
df.head(5)

```

![top 5 sceenshot](../Financial%20Data%20Analysis/asset/Dataframes/top5.png)

## Inspecting the data types of every column

In order for us to be aware of the types of data that we are handling, we could use function `dtypes`

```
df.dtypes
```

In pandas, the object data type is a general-purpose data type that can hold any kind of Python object. This is the most flexible data type in pandas, but it comes with some trade-offs in terms of performance and memory usage compared to more specific data types like int64, float64, or bool.

To continue to the next section, we want to make sure that we are working with the right data type to ensure smooth dataframe operation. 

```
df['fum'] = df['fum'].str.replace(',', '')
df['fum'] = pd.to_numeric(df['fum'], errors = 'coerce')
```

## Selecting and filterings

There are many ways to select and filter dataframe. 

### Selecting columns

Let's start with selecting a subset of data that we want from the dataframe. From the dataset, let's grab the top 5 ticker. Further, we can also access multiple columns by passing a list. Let's grab top 5 tickers and their respective name

```
df['ticker'].head(5)
df[['ticker','name']].head(5)
```
### Selecting rows

To select rows, we can use loc, iloc, and slice

```
df.loc[0]
df.iloc[0]
df[0:5]
```

### Filtering

We will discuss the three most common ways filter dataframes.

1. Query

Similar to syntax in SQL or function FILTER in Excel, we can use `query` function from `pandas`. 

Let's do two different examples. First example, we will sector to only include "Equity - Australia".
Second, we will filter the result to have FUM more than 4b.

```
df.query('sector == "Equity - Australia"')

min_fum = 4000
df.query('sector == "Equity - Australia" and fum > @min_fum')
```

2. Dataframe way

3. loc function